version: "3.7"

services:
  postgres:
    image: postgres:14
    container_name: heylo-list-database
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  webnet:
volumes:
  postgres:
    name: heylo-list-db
